import type { ResolvedTokens } from '../tokens/schema.js';

/** Emit the token layer as CSS custom properties. */
export function renderTokensCss(tokens: ResolvedTokens): string {
  const { colors, typography, spacing, radius, focus, computed } = tokens;
  const sizes = ['sm', 'base', 'lg', 'xl'] as const;
  const fontSizes = sizes
    .map((label, i) => {
      const px = Math.round(typography.baseSizePx * Math.pow(typography.scale, i - 1));
      return `  --ds-font-size-${label}: ${px}px;`;
    })
    .join('\n');
  const spaces = [1, 2, 3, 4, 6, 8]
    .map((step) => `  --ds-space-${step}: ${step * spacing.unitPx}px;`)
    .join('\n');

  return `/* Generated by design-system-generator — do not edit by hand. */
:root {
  --ds-color-primary: ${colors.primary};
  --ds-color-on-primary: ${computed.onPrimary};
  --ds-color-background: ${colors.background};
  --ds-color-surface: ${colors.surface};
  --ds-color-text: ${colors.text};
  --ds-color-text-muted: ${colors.textMuted};
  --ds-color-danger: ${colors.danger};
  --ds-color-on-danger: ${computed.onDanger};
  --ds-color-success: ${colors.success};
  --ds-color-on-success: ${computed.onSuccess};
  --ds-color-warning: ${colors.warning};
  --ds-color-on-warning: ${computed.onWarning};

  --ds-font-family: ${typography.fontFamily};
${fontSizes}

${spaces}

  --ds-radius-sm: ${radius.sm};
  --ds-radius-md: ${radius.md};
  --ds-radius-lg: ${radius.lg};

  --ds-focus-ring-width: ${focus.ringWidthPx}px;
  --ds-focus-ring-color: ${computed.focusRingColor};
}
`;
}

/** Component classes. Focus styles use :focus-visible so keyboard users always get a ring. */
export function renderStylesCss(): string {
  return `/* Generated by design-system-generator — do not edit by hand. */
@import './tokens.css';

.ds-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--ds-space-2);
  font-family: var(--ds-font-family);
  font-size: var(--ds-font-size-base);
  font-weight: 600;
  border: 2px solid transparent;
  border-radius: var(--ds-radius-md);
  cursor: pointer;
  transition: filter 120ms ease;
}
.ds-button:focus-visible,
.ds-input:focus-visible {
  outline: var(--ds-focus-ring-width) solid var(--ds-focus-ring-color);
  outline-offset: 2px;
}
.ds-button:hover:not(:disabled) {
  filter: brightness(0.92);
}
.ds-button:disabled {
  opacity: 0.55;
  cursor: not-allowed;
}
.ds-button--md {
  padding: var(--ds-space-2) var(--ds-space-4);
}
.ds-button--sm {
  padding: var(--ds-space-1) var(--ds-space-3);
  font-size: var(--ds-font-size-sm);
}
.ds-button--lg {
  padding: var(--ds-space-3) var(--ds-space-6);
  font-size: var(--ds-font-size-lg);
}
.ds-button--primary {
  background: var(--ds-color-primary);
  color: var(--ds-color-on-primary);
}
.ds-button--secondary {
  background: var(--ds-color-background);
  color: var(--ds-color-primary);
  border-color: var(--ds-color-primary);
}
.ds-button--danger {
  background: var(--ds-color-danger);
  color: var(--ds-color-on-danger);
}

.ds-field {
  display: flex;
  flex-direction: column;
  gap: var(--ds-space-1);
  font-family: var(--ds-font-family);
  max-width: 40ch;
}
.ds-field__label {
  font-size: var(--ds-font-size-sm);
  font-weight: 600;
  color: var(--ds-color-text);
}
.ds-field__description {
  font-size: var(--ds-font-size-sm);
  color: var(--ds-color-text-muted);
}
.ds-field__error {
  font-size: var(--ds-font-size-sm);
  font-weight: 600;
  color: var(--ds-color-danger);
}
.ds-input {
  font-family: var(--ds-font-family);
  font-size: var(--ds-font-size-base);
  color: var(--ds-color-text);
  background: var(--ds-color-background);
  border: 2px solid var(--ds-color-text-muted);
  border-radius: var(--ds-radius-sm);
  padding: var(--ds-space-2) var(--ds-space-3);
}
.ds-input[aria-invalid='true'] {
  border-color: var(--ds-color-danger);
}

.ds-badge {
  display: inline-block;
  font-family: var(--ds-font-family);
  font-size: var(--ds-font-size-sm);
  font-weight: 600;
  padding: var(--ds-space-1) var(--ds-space-2);
  border-radius: var(--ds-radius-lg);
}
.ds-badge--neutral {
  background: var(--ds-color-surface);
  color: var(--ds-color-text);
}
.ds-badge--success {
  background: var(--ds-color-success);
  color: var(--ds-color-on-success);
}
.ds-badge--warning {
  background: var(--ds-color-warning);
  color: var(--ds-color-on-warning);
}
.ds-badge--danger {
  background: var(--ds-color-danger);
  color: var(--ds-color-on-danger);
}

.ds-alert {
  display: flex;
  gap: var(--ds-space-3);
  font-family: var(--ds-font-family);
  font-size: var(--ds-font-size-base);
  color: var(--ds-color-text);
  background: var(--ds-color-surface);
  border-left: 4px solid var(--ds-color-primary);
  border-radius: var(--ds-radius-sm);
  padding: var(--ds-space-3) var(--ds-space-4);
}
.ds-alert--success {
  border-left-color: var(--ds-color-success);
}
.ds-alert--warning {
  border-left-color: var(--ds-color-warning);
}
.ds-alert--danger {
  border-left-color: var(--ds-color-danger);
}
.ds-alert__title {
  font-weight: 700;
  margin: 0 0 var(--ds-space-1);
}
`;
}
