import type { ResolvedTokens } from '../tokens/schema.js';
import type { ComponentFiles } from './templates.js';

/** package.json for the generated, publishable component library. */
export function renderPackageJson(tokens: ResolvedTokens): string {
  return `${JSON.stringify(
    {
      name: `${tokens.name}-design-system`,
      version: '0.0.0-development',
      description: `${tokens.name} design system — generated from design tokens with accessibility enforced at build time.`,
      license: 'MIT',
      type: 'module',
      main: './src/index.ts',
      types: './src/index.ts',
      scripts: {
        test: 'vitest run',
        storybook: 'storybook dev -p 6006',
        'build-storybook': 'storybook build',
        chromatic: 'chromatic --exit-zero-on-changes',
      },
      peerDependencies: {
        react: '>=18',
        'react-dom': '>=18',
      },
      devDependencies: {
        '@storybook/addon-a11y': '^8.6.0',
        '@storybook/addon-essentials': '^8.6.0',
        '@storybook/react': '^8.6.0',
        '@storybook/react-vite': '^8.6.0',
        '@testing-library/dom': '^10.4.0',
        '@testing-library/react': '^16.2.0',
        '@types/react': '^18.3.0',
        '@types/react-dom': '^18.3.0',
        'axe-core': '^4.10.0',
        jsdom: '^25.0.0',
        react: '^18.3.1',
        'react-dom': '^18.3.1',
        storybook: '^8.6.0',
        typescript: '^5.7.3',
        vite: '^5.4.0',
        vitest: '^3.0.5',
      },
    },
    null,
    2,
  )}\n`;
}

export function renderVitestConfig(): string {
  return `// Generated by design-system-generator.
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'jsdom',
  },
});
`;
}

export function renderTsConfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        jsx: 'react-jsx',
        lib: ['ES2022', 'DOM', 'DOM.Iterable'],
        strict: true,
        skipLibCheck: true,
        noEmit: true,
        types: ['vitest/globals'],
      },
      include: ['src', '.storybook'],
    },
    null,
    2,
  )}\n`;
}

/**
 * Shared axe-core test helper. The color-contrast rule is disabled because
 * jsdom does not paint pixels — contrast is instead enforced at generation
 * time from the token values themselves (see the generator's contrast gate).
 */
export function renderAxeHelper(): string {
  return `// Generated by design-system-generator.
import axe from 'axe-core';

export async function expectNoAxeViolations(container: HTMLElement): Promise<void> {
  const results = await axe.run(container, {
    rules: {
      // jsdom cannot compute rendered colors; contrast is verified from the
      // design tokens at generation time instead.
      'color-contrast': { enabled: false },
    },
  });
  if (results.violations.length > 0) {
    const summary = results.violations
      .map((v) => v.id + ': ' + v.help + ' (' + v.nodes.length + ' nodes)')
      .join('\\n');
    throw new Error('axe-core violations found:\\n' + summary);
  }
}
`;
}

export function renderIndexTs(components: ComponentFiles[]): string {
  return (
    '// Generated by design-system-generator — do not edit by hand.\n' +
    components
      .map((c) => `export { ${c.name}, type ${c.name}Props } from './${c.name}/${c.name}';`)
      .join('\n') +
    '\n'
  );
}

export function renderStorybookMain(): string {
  return `// Generated by design-system-generator.
import type { StorybookConfig } from '@storybook/react-vite';

const config: StorybookConfig = {
  stories: ['../src/**/*.stories.tsx'],
  addons: ['@storybook/addon-essentials', '@storybook/addon-a11y'],
  framework: { name: '@storybook/react-vite', options: {} },
};

export default config;
`;
}

export function renderStorybookPreview(hasDarkMode: boolean): string {
  if (!hasDarkMode) {
    return `// Generated by design-system-generator.
import type { Preview } from '@storybook/react';
import '../src/tokens.css';
import '../src/styles.css';

const preview: Preview = {
  parameters: {
    a11y: { test: 'error' },
  },
};

export default preview;
`;
  }

  return `// Generated by design-system-generator.
import * as React from 'react';
import type { Preview } from '@storybook/react';
import '../src/tokens.css';
import '../src/styles.css';

export const globalTypes = {
  theme: {
    description: 'Color theme',
    defaultValue: 'light',
    toolbar: {
      title: 'Theme',
      icon: 'circlehollow',
      items: [
        { value: 'light', icon: 'circlehollow', title: 'Light' },
        { value: 'dark', icon: 'circle', title: 'Dark' },
      ],
      dynamicTitle: true,
    },
  },
};

const preview: Preview = {
  parameters: {
    a11y: { test: 'error' },
  },
  decorators: [
    (Story, context) => {
      document.documentElement.setAttribute('data-theme', context.globals.theme ?? 'light');
      return React.createElement(
        'div',
        {
          style: {
            background: 'var(--ds-color-background)',
            color: 'var(--ds-color-text)',
            minHeight: '100vh',
            padding: '1rem',
          },
        },
        React.createElement(Story),
      );
    },
  ],
};

export default preview;
`;
}

export function renderGeneratedReadme(tokens: ResolvedTokens, components: ComponentFiles[]): string {
  const list = components.map((c) => `- **${c.name}** — see \`src/${c.name}/${c.name}.docs.md\``).join('\n');
  const theming = tokens.darkColors
    ? `
## Theming

This system ships a dark palette alongside the light one, validated against
WCAG AA independently (see \`src/tokens.css\`). It applies in three ways:

- **Automatically**, via \`prefers-color-scheme: dark\`, when the page hasn't set a theme explicitly.
- **Explicitly**, by setting \`data-theme="dark"\` or \`data-theme="light"\` on \`<html>\` (or any ancestor) — this overrides the OS preference.
- **In Storybook**, via the "Theme" toolbar toggle.

No JavaScript is required for the automatic or explicit cases — every
component reads color through the same CSS custom properties, so switching
\`data-theme\` re-themes the whole library instantly.
`
    : '';

  return `# ${tokens.name}-design-system

A React + TypeScript component library generated from design tokens by
[design-system-generator](https://github.com/benmcosker/design-system-generator).

## Components

${list}

## Accessibility

- Token colors were verified against WCAG AA contrast ratios **before generation** — the generator refuses to emit an inaccessible palette.
- Every component ships with an axe-core test (\`npm test\`).
- Storybook runs with \`@storybook/addon-a11y\` set to fail on violations.
${theming}
## Scripts

| Command | What it does |
| --- | --- |
| \`npm test\` | Runs axe-core accessibility tests for every component (vitest + jsdom) |
| \`npm run storybook\` | Auto-generated Storybook docs with the a11y addon |
| \`npm run chromatic\` | Visual regression via Chromatic (set \`CHROMATIC_PROJECT_TOKEN\`) |

## Publishing

The package is set up for semantic versioning: version \`0.0.0-development\`
is replaced at release time. Wire it into CI with
[semantic-release](https://github.com/semantic-release/semantic-release) and
conventional commits.
`;
}
