import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import YAML from 'yaml';
import type { ResolvedTokens, TokenSpec } from '../tokens/schema.js';
import type { ComponentFiles } from './templates.js';

/**
 * The generator's own published version, so the devDependency it emits into
 * generated systems tracks whatever version is actually generating them
 * instead of a value that goes stale the moment semantic-release bumps it.
 */
function getOwnVersion(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  const pkg = JSON.parse(readFileSync(join(here, '..', '..', 'package.json'), 'utf8')) as {
    version: string;
  };
  return pkg.version;
}

/** package.json for the generated, publishable component library. */
export function renderPackageJson(tokens: ResolvedTokens): string {
  const generatorVersion = getOwnVersion();
  return `${JSON.stringify(
    {
      name: `${tokens.name}-design-system`,
      version: '0.0.0-development',
      description: `${tokens.name} design system — generated from design tokens with accessibility enforced at build time.`,
      license: 'MIT',
      type: 'module',
      main: './src/index.ts',
      types: './src/index.ts',
      scripts: {
        test: 'vitest run',
        check: 'dsg check tokens.yaml',
        storybook: 'storybook dev -p 6006',
        'build-storybook': 'storybook build',
        chromatic: 'chromatic --exit-zero-on-changes',
      },
      peerDependencies: {
        react: '>=18',
        'react-dom': '>=18',
      },
      devDependencies: {
        '@benjaminmcosker/design-system-generator':
          generatorVersion === '0.0.0-development' ? '*' : `^${generatorVersion}`,
        '@storybook/addon-a11y': '^8.6.0',
        '@storybook/addon-essentials': '^8.6.0',
        '@storybook/react': '^8.6.0',
        '@storybook/react-vite': '^8.6.0',
        '@testing-library/dom': '^10.4.0',
        '@testing-library/react': '^16.2.0',
        '@testing-library/user-event': '^14.5.0',
        '@types/react': '^18.3.0',
        '@types/react-dom': '^18.3.0',
        'axe-core': '^4.10.0',
        jsdom: '^25.0.0',
        react: '^18.3.1',
        'react-dom': '^18.3.1',
        storybook: '^8.6.0',
        typescript: '^5.7.3',
        vite: '^5.4.0',
        vitest: '^3.0.5',
      },
    },
    null,
    2,
  )}\n`;
}

export function renderVitestConfig(): string {
  return `// Generated by design-system-generator.
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'jsdom',
  },
});
`;
}

export function renderTsConfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        jsx: 'react-jsx',
        lib: ['ES2022', 'DOM', 'DOM.Iterable'],
        strict: true,
        skipLibCheck: true,
        noEmit: true,
        types: ['vitest/globals'],
      },
      include: ['src', '.storybook'],
    },
    null,
    2,
  )}\n`;
}

/**
 * Shared axe-core test helper. The color-contrast rule is disabled because
 * jsdom does not paint pixels — contrast is instead enforced at generation
 * time from the token values themselves (see the generator's contrast gate).
 */
export function renderAxeHelper(): string {
  return `// Generated by design-system-generator.
import axe from 'axe-core';

export async function expectNoAxeViolations(container: HTMLElement): Promise<void> {
  const results = await axe.run(container, {
    rules: {
      // jsdom cannot compute rendered colors; contrast is verified from the
      // design tokens at generation time instead.
      'color-contrast': { enabled: false },
    },
  });
  if (results.violations.length > 0) {
    const summary = results.violations
      .map((v) => v.id + ': ' + v.help + ' (' + v.nodes.length + ' nodes)')
      .join('\\n');
    throw new Error('axe-core violations found:\\n' + summary);
  }
}
`;
}

export function renderIndexTs(components: ComponentFiles[]): string {
  return (
    '// Generated by design-system-generator — do not edit by hand.\n' +
    components
      .map((c) => `export { ${c.name}, type ${c.name}Props } from './${c.name}/${c.name}';`)
      .join('\n') +
    '\n'
  );
}

export function renderStorybookMain(): string {
  return `// Generated by design-system-generator.
import type { StorybookConfig } from '@storybook/react-vite';

const config: StorybookConfig = {
  stories: ['../src/**/*.stories.tsx'],
  addons: ['@storybook/addon-essentials', '@storybook/addon-a11y'],
  framework: { name: '@storybook/react-vite', options: {} },
};

export default config;
`;
}

export function renderStorybookPreview(): string {
  return `// Generated by design-system-generator.
import type { Preview } from '@storybook/react';
import '../src/tokens.css';
import '../src/styles.css';

const preview: Preview = {
  parameters: {
    a11y: { test: 'error' },
  },
};

export default preview;
`;
}

/**
 * The source-of-truth token spec, written into the generated repo as
 * tokens.yaml so `dsg check tokens.yaml` can re-validate WCAG AA contrast in
 * the generated system's own CI. The `computed` values are dropped — they're
 * re-derived by resolveTokens() on every check, not part of the spec itself.
 */
export function renderTokenSpecYaml(tokens: ResolvedTokens): string {
  const { computed: _computed, ...spec } = tokens;
  const specOnly: TokenSpec = spec;
  return (
    '# Generated by design-system-generator — the source-of-truth token spec\n' +
    '# for this design system. Run `npm run check` (or `dsg check tokens.yaml`)\n' +
    '# to re-validate WCAG AA contrast after editing colors here.\n' +
    YAML.stringify(specOnly)
  );
}

/**
 * CI workflow for the generated repo: a required, non-overridable WCAG AA
 * contrast gate. No continue-on-error, no skip path — a failing check fails
 * the build.
 */
export function renderContrastWorkflow(): string {
  return `# Generated by design-system-generator.
#
# A failing WCAG AA contrast check is a hard build failure — no
# continue-on-error, no skip path. Pair this with branch protection
# ("Include administrators") so it can't be bypassed; see the README's
# "Enforce the gate (no override)" section for the one-time setup command.
name: Contrast gate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  contrast:
    name: WCAG AA contrast gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npx dsg check tokens.yaml
`;
}

export function renderGeneratedReadme(tokens: ResolvedTokens, components: ComponentFiles[]): string {
  const list = components.map((c) => `- **${c.name}** — see \`src/${c.name}/${c.name}.docs.md\``).join('\n');
  return `# ${tokens.name}-design-system

A React + TypeScript component library generated from design tokens by
[design-system-generator](https://github.com/benmcosker/design-system-generator).

## Components

${list}

## Accessibility

- Token colors were verified against WCAG AA contrast ratios **before generation** — the generator refuses to emit an inaccessible palette.
- Every component ships with an axe-core test (\`npm test\`).
- Storybook runs with \`@storybook/addon-a11y\` set to fail on violations.
- \`.github/workflows/contrast.yml\` re-runs the same WCAG AA check
  (\`dsg check tokens.yaml\`) on every push and PR — see below to make it
  non-overridable.

## Scripts

| Command | What it does |
| --- | --- |
| \`npm test\` | Runs axe-core accessibility tests for every component (vitest + jsdom) |
| \`npm run check\` | Re-validates \`tokens.yaml\` against WCAG AA contrast |
| \`npm run storybook\` | Auto-generated Storybook docs with the a11y addon |
| \`npm run chromatic\` | Visual regression via Chromatic (set \`CHROMATIC_PROJECT_TOKEN\`) |

## Enforce the gate (no override)

\`.github/workflows/contrast.yml\` makes a failing contrast check a hard CI
failure, but CI alone doesn't stop someone with admin rights from merging a
red PR. Run this once (requires the [\`gh\`](https://cli.github.com/) CLI and
admin on the repo) to make the \`contrast\` check required and
non-bypassable, including for admins:

\`\`\`bash
gh api -X PUT repos/OWNER/REPO/branches/main/protection \\
  -F required_status_checks.strict=true \\
  -F 'required_status_checks.contexts[]=contrast' \\
  -F enforce_admins=true \\
  -F required_pull_request_reviews.required_approving_review_count=0 \\
  -F restrictions=
\`\`\`

Replace \`OWNER/REPO\` with this repository. \`enforce_admins=true\` is the
part that removes the override — without it, repo admins can still merge
past a red check.

## Publishing

The package is set up for semantic versioning: version \`0.0.0-development\`
is replaced at release time. Wire it into CI with
[semantic-release](https://github.com/semantic-release/semantic-release) and
conventional commits.
`;
}
