import type { ResolvedTokens } from '../tokens/schema.js';
import { fontSizeLadder } from './css.js';

/**
 * The shadcn/ui target: a Tailwind v4 theme generated from the token spec.
 * `:root` holds shadcn's CSS variables; `@theme inline` exposes them as
 * Tailwind utilities (`bg-primary`, `text-muted-foreground`, …).
 */

export interface ShadcnRenderOptions {
  /** Token file name shown in the header comment, e.g. `tokens.yaml`. */
  source?: string;
}

/** shadcn variable name (without `--`) → value, in emission order. */
export function shadcnRootVars(tokens: ResolvedTokens): Array<[string, string]> {
  const { colors, radius, computed } = tokens;
  return [
    ['background', colors.background],
    ['foreground', colors.text],
    ['card', colors.surface],
    ['card-foreground', colors.text],
    ['popover', colors.surface],
    ['popover-foreground', colors.text],
    ['primary', colors.primary],
    ['primary-foreground', computed.onPrimary],
    ['secondary', computed.secondary],
    ['secondary-foreground', computed.onSecondary],
    ['muted', computed.muted],
    ['muted-foreground', colors.textMuted],
    ['accent', computed.accent],
    ['accent-foreground', computed.onAccent],
    ['destructive', colors.danger],
    ['destructive-foreground', computed.onDanger],
    ['success', colors.success],
    ['success-foreground', computed.onSuccess],
    ['warning', colors.warning],
    ['warning-foreground', computed.onWarning],
    ['border', computed.border],
    ['input', computed.input],
    ['ring', computed.focusRingColor],
    ['radius', radius.md],
    ...computed.chart.map((color, i): [string, string] => [`chart-${i + 1}`, color]),
    ['sidebar', colors.surface],
    ['sidebar-foreground', colors.text],
    ['sidebar-primary', colors.primary],
    ['sidebar-primary-foreground', computed.onPrimary],
    ['sidebar-accent', computed.accent],
    ['sidebar-accent-foreground', computed.onAccent],
    ['sidebar-border', computed.border],
    ['sidebar-ring', computed.focusRingColor],
  ];
}

/** Tailwind v4 `@theme inline` entries (without `--`) → value. */
export function shadcnThemeVars(tokens: ResolvedTokens): Array<[string, string]> {
  const { typography, spacing, radius } = tokens;
  const colorVars = shadcnRootVars(tokens)
    .map(([name]) => name)
    .filter((name) => name !== 'radius')
    .map((name): [string, string] => [`color-${name}`, `var(--${name})`]);
  return [
    ...colorVars,
    ['radius-sm', radius.sm],
    ['radius-md', radius.md],
    ['radius-lg', radius.lg],
    ['font-sans', typography.fontFamily],
    ...fontSizeLadder(typography).map(([label, px]): [string, string] => [`text-${label}`, `${px}px`]),
    ['spacing', `${spacing.unitPx}px`],
  ];
}

/** The header comment. Drift checks ignore it, so it can name the source file. */
export function shadcnThemeHeader(options: ShadcnRenderOptions = {}): string {
  const source = options.source ?? 'tokens.yaml';
  return `/* Generated by design-system-generator (target: shadcn) — do not edit by hand.
   Source: ${source} · Regenerate: dsg generate ${source} --target shadcn */`;
}

/** `theme.css`: shadcn's `:root` variables plus the Tailwind v4 bridge. */
export function renderShadcnThemeCss(tokens: ResolvedTokens, options: ShadcnRenderOptions = {}): string {
  const root = shadcnRootVars(tokens)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join('\n');
  const theme = shadcnThemeVars(tokens)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join('\n');
  return `${shadcnThemeHeader(options)}
:root {
${root}
}

@theme inline {
${theme}
}
`;
}

/** Strip the leading header comment so two themes can be compared on content alone. */
export function stripShadcnHeader(css: string): string {
  return css.replace(/\r\n/g, '\n').replace(/^\s*\/\*[\s\S]*?\*\/\s*\n/, '');
}

/**
 * A shadcn registry item (`registry:theme`) carrying the same variables, so
 * a consumer can run `npx shadcn add <path-or-url>` instead of copying CSS.
 */
export function renderShadcnRegistryItem(tokens: ResolvedTokens): string {
  const item = {
    $schema: 'https://ui.shadcn.com/schema/registry-item.json',
    name: `${tokens.name}-theme`,
    type: 'registry:theme',
    title: `${tokens.name} theme`,
    description: `Theme generated by design-system-generator from the ${tokens.name} token spec (WCAG AA contrast-checked).`,
    cssVars: {
      theme: Object.fromEntries(shadcnThemeVars(tokens)),
      light: Object.fromEntries(shadcnRootVars(tokens)),
    },
  };
  return JSON.stringify(item, null, 2) + '\n';
}

/** README for the generated theme folder. */
export function renderShadcnReadme(tokens: ResolvedTokens, options: ShadcnRenderOptions = {}): string {
  const source = options.source ?? 'tokens.yaml';
  return `# ${tokens.name} shadcn/ui theme

Generated by [design-system-generator](https://github.com/benmcosker/design-system-generator)
from \`${source}\`. Every color pairing shadcn/ui components use was checked against
WCAG AA before this was written. Don't edit these files by hand: change the tokens and
regenerate.

## Install

Either paste \`theme.css\` into \`app/globals.css\` right after \`@import "tailwindcss";\`,
or install the registry item:

\`\`\`bash
npx shadcn add ./registry-item.json
\`\`\`

## Keep it in sync (CI)

\`\`\`bash
dsg check ${source} --theme path/to/theme.css
\`\`\`

This fails if the committed theme no longer matches the tokens, for example after
someone edits a color by hand. That keeps every palette change behind the contrast check.

## Focus rings: one change to make

shadcn/ui components draw focus rings at reduced opacity (e.g. \`focus-visible:ring-ring/50\`).
At 50% opacity the ring no longer has the contrast this theme was checked for. In the
components you copy in, change those classes to full-opacity \`ring-ring\`. This theme sets
colors only; it can't change component class names.
`;
}
