import type { ResolvedTokens } from '../tokens/schema.js';

export interface ComponentFiles {
  name: string;
  component: string;
  story: string;
  test: string;
}

const HEADER = '// Generated by design-system-generator — do not edit by hand.\n';

function axeTest(name: string, renderCalls: string): string {
  return `${HEADER}import { describe, it } from 'vitest';
import { render } from '@testing-library/react';
import { expectNoAxeViolations } from '../testing/axe';
import { ${name} } from './${name}';

describe('${name} accessibility', () => {
${renderCalls}
});
`;
}

export function buttonTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  /** Visual style. Every variant meets WCAG AA contrast by construction. */
  variant?: 'primary' | 'secondary' | 'danger';
  size?: 'sm' | 'md' | 'lg';
  /** Announces a busy state to assistive technology and blocks interaction. */
  loading?: boolean;
}

export function Button({
  variant = 'primary',
  size = 'md',
  loading = false,
  type = 'button',
  disabled,
  className,
  children,
  ...rest
}: ButtonProps) {
  const classes = ['ds-button', 'ds-button--' + variant, 'ds-button--' + size, className]
    .filter(Boolean)
    .join(' ');
  return (
    <button
      type={type}
      className={classes}
      disabled={disabled || loading}
      aria-busy={loading || undefined}
      {...rest}
    >
      {children}
    </button>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { Button } from './Button';

const meta = {
  title: 'Components/Button',
  component: Button,
  tags: ['autodocs'],
  args: { children: 'Save changes' },
} satisfies Meta<typeof Button>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Primary: Story = {};
export const Secondary: Story = { args: { variant: 'secondary' } };
export const Danger: Story = { args: { variant: 'danger', children: 'Delete account' } };
export const Loading: Story = { args: { loading: true, children: 'Saving…' } };
export const Small: Story = { args: { size: 'sm' } };
export const Large: Story = { args: { size: 'lg' } };
`;

  const test = axeTest(
    'Button',
    `  it('has no axe violations across variants', async () => {
    const { container } = render(
      <main>
        <Button>Primary</Button>
        <Button variant="secondary">Secondary</Button>
        <Button variant="danger">Danger</Button>
        <Button loading>Loading</Button>
        <Button disabled>Disabled</Button>
      </main>,
    );
    await expectNoAxeViolations(container);
  });
`,
  );

  return { name: 'Button', component, story, test };
}

export function textFieldTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface TextFieldProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'id' | 'aria-describedby'> {
  /** Visible label — always rendered and programmatically associated. */
  label: string;
  /** Optional helper text, linked via aria-describedby. */
  description?: string;
  /** Validation message. Sets aria-invalid and is announced politely. */
  error?: string;
}

export function TextField({ label, description, error, required, ...rest }: TextFieldProps) {
  const id = React.useId();
  const descriptionId = id + '-description';
  const errorId = id + '-error';
  const describedBy =
    [description ? descriptionId : null, error ? errorId : null].filter(Boolean).join(' ') ||
    undefined;

  return (
    <div className="ds-field">
      <label className="ds-field__label" htmlFor={id}>
        {label}
        {required ? <span aria-hidden="true"> *</span> : null}
      </label>
      {description ? (
        <p className="ds-field__description" id={descriptionId}>
          {description}
        </p>
      ) : null}
      <input
        id={id}
        className="ds-input"
        aria-describedby={describedBy}
        aria-invalid={error ? true : undefined}
        required={required}
        {...rest}
      />
      <p className="ds-field__error" id={errorId} aria-live="polite">
        {error ?? ''}
      </p>
    </div>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { TextField } from './TextField';

const meta = {
  title: 'Components/TextField',
  component: TextField,
  tags: ['autodocs'],
  args: { label: 'Email address' },
} satisfies Meta<typeof TextField>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
export const WithDescription: Story = {
  args: { description: "We'll only use this to send order updates." },
};
export const Required: Story = { args: { required: true } };
export const WithError: Story = {
  args: { error: 'Enter a valid email address.', defaultValue: 'not-an-email' },
};
`;

  const test = axeTest(
    'TextField',
    `  it('has no axe violations in default, described, and error states', async () => {
    const { container } = render(
      <main>
        <TextField label="Email address" />
        <TextField label="Password" description="Must be at least 12 characters." required />
        <TextField label="Username" error="That username is taken." defaultValue="ben" />
      </main>,
    );
    await expectNoAxeViolations(container);
  });
`,
  );

  return { name: 'TextField', component, story, test };
}

export function badgeTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  tone?: 'neutral' | 'success' | 'warning' | 'danger';
}

export function Badge({ tone = 'neutral', className, children, ...rest }: BadgeProps) {
  const classes = ['ds-badge', 'ds-badge--' + tone, className].filter(Boolean).join(' ');
  return (
    <span className={classes} {...rest}>
      {children}
    </span>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { Badge } from './Badge';

const meta = {
  title: 'Components/Badge',
  component: Badge,
  tags: ['autodocs'],
  args: { children: 'Active' },
} satisfies Meta<typeof Badge>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Neutral: Story = {};
export const Success: Story = { args: { tone: 'success', children: 'Paid' } };
export const Warning: Story = { args: { tone: 'warning', children: 'Pending' } };
export const Danger: Story = { args: { tone: 'danger', children: 'Overdue' } };
`;

  const test = axeTest(
    'Badge',
    `  it('has no axe violations across tones', async () => {
    const { container } = render(
      <main>
        <Badge>Neutral</Badge>
        <Badge tone="success">Paid</Badge>
        <Badge tone="warning">Pending</Badge>
        <Badge tone="danger">Overdue</Badge>
      </main>,
    );
    await expectNoAxeViolations(container);
  });
`,
  );

  return { name: 'Badge', component, story, test };
}

export function alertTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface AlertProps extends React.HTMLAttributes<HTMLDivElement> {
  tone?: 'info' | 'success' | 'warning' | 'danger';
  title?: string;
}

/**
 * Danger alerts use role="alert" (assertive) because they demand attention;
 * everything else uses role="status" (polite) to avoid interrupting
 * screen-reader users mid-task.
 */
export function Alert({ tone = 'info', title, className, children, ...rest }: AlertProps) {
  const classes = ['ds-alert', 'ds-alert--' + tone, className].filter(Boolean).join(' ');
  const role = tone === 'danger' ? 'alert' : 'status';
  return (
    <div className={classes} role={role} {...rest}>
      <div>
        {title ? <p className="ds-alert__title">{title}</p> : null}
        {children}
      </div>
    </div>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { Alert } from './Alert';

const meta = {
  title: 'Components/Alert',
  component: Alert,
  tags: ['autodocs'],
  args: { title: 'Heads up', children: 'Your trial ends in 3 days.' },
} satisfies Meta<typeof Alert>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Info: Story = {};
export const Success: Story = {
  args: { tone: 'success', title: 'Saved', children: 'Your changes are live.' },
};
export const Warning: Story = {
  args: { tone: 'warning', title: 'Storage almost full', children: 'You have 2% remaining.' },
};
export const Danger: Story = {
  args: { tone: 'danger', title: 'Payment failed', children: 'Update your card to continue.' },
};
`;

  const test = axeTest(
    'Alert',
    `  it('has no axe violations across tones', async () => {
    const { container } = render(
      <main>
        <Alert title="Heads up">Your trial ends in 3 days.</Alert>
        <Alert tone="success" title="Saved">Your changes are live.</Alert>
        <Alert tone="warning" title="Storage almost full">You have 2% remaining.</Alert>
        <Alert tone="danger" title="Payment failed">Update your card to continue.</Alert>
      </main>,
    );
    await expectNoAxeViolations(container);
  });
`,
  );

  return { name: 'Alert', component, story, test };
}

export function checkboxTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface CheckboxProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type' | 'id'> {
  /** Visible label — always rendered and programmatically associated. */
  label: string;
  /** Optional helper text, linked via aria-describedby. */
  description?: string;
}

export function Checkbox({ label, description, className, ...rest }: CheckboxProps) {
  const id = React.useId();
  const descriptionId = id + '-description';

  return (
    <div className={['ds-checkbox', className].filter(Boolean).join(' ')}>
      <input
        id={id}
        type="checkbox"
        className="ds-checkbox__input"
        aria-describedby={description ? descriptionId : undefined}
        {...rest}
      />
      <label className="ds-checkbox__label" htmlFor={id}>
        {label}
      </label>
      {description ? (
        <p className="ds-checkbox__description" id={descriptionId}>
          {description}
        </p>
      ) : null}
    </div>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { Checkbox } from './Checkbox';

const meta = {
  title: 'Components/Checkbox',
  component: Checkbox,
  tags: ['autodocs'],
  args: { label: 'Email me about product updates' },
} satisfies Meta<typeof Checkbox>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
export const Checked: Story = { args: { defaultChecked: true } };
export const WithDescription: Story = {
  args: { description: 'About once a month. Unsubscribe anytime.' },
};
export const Disabled: Story = { args: { disabled: true } };
`;

  const test = axeTest(
    'Checkbox',
    `  it('has no axe violations across states', async () => {
    const { container } = render(
      <main>
        <Checkbox label="Default" />
        <Checkbox label="Checked" defaultChecked />
        <Checkbox label="Described" description="Extra context for this option." />
        <Checkbox label="Disabled" disabled />
      </main>,
    );
    await expectNoAxeViolations(container);
  });
`,
  );

  return { name: 'Checkbox', component, story, test };
}

export function switchTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface SwitchProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type' | 'id' | 'role'> {
  /** Visible label — always rendered and programmatically associated. */
  label: string;
  /** Optional helper text, linked via aria-describedby. */
  description?: string;
}

/**
 * A native checkbox with role="switch" — screen readers announce it as a
 * toggle, and it keeps the keyboard and state handling of a real form
 * control instead of a hand-rolled div with custom key bindings.
 */
export function Switch({ label, description, className, ...rest }: SwitchProps) {
  const id = React.useId();
  const descriptionId = id + '-description';

  return (
    <div className={['ds-switch', className].filter(Boolean).join(' ')}>
      <input
        id={id}
        type="checkbox"
        role="switch"
        className="ds-switch__input"
        aria-describedby={description ? descriptionId : undefined}
        {...rest}
      />
      <label className="ds-switch__label" htmlFor={id}>
        {label}
      </label>
      {description ? (
        <p className="ds-switch__description" id={descriptionId}>
          {description}
        </p>
      ) : null}
    </div>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { Switch } from './Switch';

const meta = {
  title: 'Components/Switch',
  component: Switch,
  tags: ['autodocs'],
  args: { label: 'Enable two-factor authentication' },
} satisfies Meta<typeof Switch>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
export const On: Story = { args: { defaultChecked: true } };
export const WithDescription: Story = {
  args: { description: "You'll need an authenticator app to sign in." },
};
export const Disabled: Story = { args: { disabled: true } };
`;

  const test = axeTest(
    'Switch',
    `  it('has no axe violations across states', async () => {
    const { container } = render(
      <main>
        <Switch label="Default" />
        <Switch label="On" defaultChecked />
        <Switch label="Described" description="Extra context for this option." />
        <Switch label="Disabled" disabled />
      </main>,
    );
    await expectNoAxeViolations(container);
  });
`,
  );

  return { name: 'Switch', component, story, test };
}

export function radioGroupTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface RadioOption {
  value: string;
  label: string;
}

export interface RadioGroupProps
  extends Omit<React.FieldsetHTMLAttributes<HTMLFieldSetElement>, 'onChange'> {
  /** Rendered as the fieldset's <legend> — announced once for the whole group. */
  legend: string;
  name: string;
  options: RadioOption[];
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  required?: boolean;
}

/**
 * A native <fieldset>/<legend> group of radio inputs. Arrow-key navigation
 * between options is handled by the browser for free because they're real
 * radio inputs sharing one \`name\` — no roving-tabindex code needed.
 */
export function RadioGroup({
  legend,
  name,
  options,
  value,
  defaultValue,
  onChange,
  disabled,
  required,
  className,
  ...rest
}: RadioGroupProps) {
  return (
    <fieldset className={['ds-radio-group', className].filter(Boolean).join(' ')} {...rest}>
      <legend className="ds-radio-group__legend">
        {legend}
        {required ? <span aria-hidden="true"> *</span> : null}
      </legend>
      {options.map((option) => (
        <label key={option.value} className="ds-radio-group__option">
          <input
            type="radio"
            className="ds-radio-group__input"
            name={name}
            value={option.value}
            checked={value !== undefined ? value === option.value : undefined}
            defaultChecked={
              value === undefined && defaultValue !== undefined
                ? defaultValue === option.value
                : undefined
            }
            disabled={disabled}
            required={required}
            onChange={onChange ? () => onChange(option.value) : undefined}
          />
          {option.label}
        </label>
      ))}
    </fieldset>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { RadioGroup } from './RadioGroup';

const plans = [
  { value: 'free', label: 'Free' },
  { value: 'pro', label: 'Pro' },
  { value: 'team', label: 'Team' },
];

const meta = {
  title: 'Components/RadioGroup',
  component: RadioGroup,
  tags: ['autodocs'],
  args: { legend: 'Plan', name: 'plan', options: plans },
} satisfies Meta<typeof RadioGroup>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
export const WithDefault: Story = { args: { defaultValue: 'pro' } };
export const Required: Story = { args: { required: true } };
export const Disabled: Story = { args: { disabled: true, defaultValue: 'free' } };
`;

  const test = axeTest(
    'RadioGroup',
    `  const plans = [
    { value: 'free', label: 'Free' },
    { value: 'pro', label: 'Pro' },
    { value: 'team', label: 'Team' },
  ];

  it('has no axe violations across states', async () => {
    const { container } = render(
      <main>
        <RadioGroup legend="Plan" name="plan-default" options={plans} />
        <RadioGroup legend="Plan (preselected)" name="plan-preselected" options={plans} defaultValue="pro" />
        <RadioGroup legend="Plan (required)" name="plan-required" options={plans} required />
        <RadioGroup legend="Plan (disabled)" name="plan-disabled" options={plans} disabled defaultValue="free" />
      </main>,
    );
    await expectNoAxeViolations(container);
  });
`,
  );

  return { name: 'RadioGroup', component, story, test };
}

export function selectTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface SelectOption {
  value: string;
  label: string;
}

export interface SelectProps
  extends Omit<React.SelectHTMLAttributes<HTMLSelectElement>, 'id' | 'aria-describedby'> {
  /** Visible label — always rendered and programmatically associated. */
  label: string;
  options: SelectOption[];
  /** Optional helper text, linked via aria-describedby. */
  description?: string;
  /** Validation message. Sets aria-invalid and is announced politely. */
  error?: string;
}

/** A native <select> — full keyboard support and platform picker UI for free. */
export function Select({ label, options, description, error, required, ...rest }: SelectProps) {
  const id = React.useId();
  const descriptionId = id + '-description';
  const errorId = id + '-error';
  const describedBy =
    [description ? descriptionId : null, error ? errorId : null].filter(Boolean).join(' ') ||
    undefined;

  return (
    <div className="ds-field">
      <label className="ds-field__label" htmlFor={id}>
        {label}
        {required ? <span aria-hidden="true"> *</span> : null}
      </label>
      {description ? (
        <p className="ds-field__description" id={descriptionId}>
          {description}
        </p>
      ) : null}
      <select
        id={id}
        className="ds-select"
        aria-describedby={describedBy}
        aria-invalid={error ? true : undefined}
        required={required}
        {...rest}
      >
        {options.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
      <p className="ds-field__error" id={errorId} aria-live="polite">
        {error ?? ''}
      </p>
    </div>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { Select } from './Select';

const countries = [
  { value: 'us', label: 'United States' },
  { value: 'gb', label: 'United Kingdom' },
  { value: 'de', label: 'Germany' },
];

const meta = {
  title: 'Components/Select',
  component: Select,
  tags: ['autodocs'],
  args: { label: 'Country', options: countries },
} satisfies Meta<typeof Select>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
export const WithDescription: Story = {
  args: { description: 'Used to calculate shipping and tax.' },
};
export const Required: Story = { args: { required: true } };
export const WithError: Story = { args: { error: 'Select a country to continue.' } };
`;

  const test = axeTest(
    'Select',
    `  const countries = [
    { value: 'us', label: 'United States' },
    { value: 'gb', label: 'United Kingdom' },
    { value: 'de', label: 'Germany' },
  ];

  it('has no axe violations in default, described, and error states', async () => {
    const { container } = render(
      <main>
        <Select label="Country" options={countries} />
        <Select label="Region" options={countries} description="Used for shipping." required />
        <Select label="Currency" options={countries} error="Select a currency." />
      </main>,
    );
    await expectNoAxeViolations(container);
  });
`,
  );

  return { name: 'Select', component, story, test };
}

export function tabsTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface TabItem {
  id: string;
  label: string;
  content: React.ReactNode;
}

export interface TabsProps {
  /** Accessible name for the tablist itself. */
  label: string;
  items: TabItem[];
  activeId?: string;
  defaultActiveId?: string;
  onChange?: (id: string) => void;
}

const ARROW_KEYS = ['ArrowLeft', 'ArrowRight', 'Home', 'End'];

/**
 * WAI-ARIA APG tabs pattern with automatic activation: arrow keys move
 * focus *and* selection together. Only the active tab sits in the Tab
 * order (roving tabIndex) — arrow keys, not Tab, move between tabs.
 */
export function Tabs({ label, items, activeId, defaultActiveId, onChange }: TabsProps) {
  const base = React.useId();
  const [internalActiveId, setInternalActiveId] = React.useState(
    defaultActiveId ?? items[0]?.id,
  );
  const currentId = activeId ?? internalActiveId;
  const tabRefs = React.useRef<Record<string, HTMLButtonElement | null>>({});

  const selectTab = (id: string) => {
    if (activeId === undefined) {
      setInternalActiveId(id);
    }
    onChange?.(id);
  };

  const handleKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if (!ARROW_KEYS.includes(event.key)) return;
    const currentIndex = items.findIndex((item) => item.id === currentId);
    if (currentIndex === -1) return;

    let nextIndex: number;
    if (event.key === 'ArrowRight') {
      nextIndex = (currentIndex + 1) % items.length;
    } else if (event.key === 'ArrowLeft') {
      nextIndex = (currentIndex - 1 + items.length) % items.length;
    } else if (event.key === 'Home') {
      nextIndex = 0;
    } else {
      nextIndex = items.length - 1;
    }

    event.preventDefault();
    const next = items[nextIndex];
    if (!next) return;
    selectTab(next.id);
    tabRefs.current[next.id]?.focus();
  };

  return (
    <div className="ds-tabs">
      <div
        className="ds-tabs__list"
        role="tablist"
        aria-label={label}
        onKeyDown={handleKeyDown}
      >
        {items.map((item) => {
          const isActive = item.id === currentId;
          return (
            <button
              key={item.id}
              type="button"
              ref={(el) => {
                tabRefs.current[item.id] = el;
              }}
              id={base + '-tab-' + item.id}
              className="ds-tabs__tab"
              role="tab"
              aria-selected={isActive}
              aria-controls={base + '-panel-' + item.id}
              tabIndex={isActive ? 0 : -1}
              onClick={() => selectTab(item.id)}
            >
              {item.label}
            </button>
          );
        })}
      </div>
      {items.map((item) => {
        const isActive = item.id === currentId;
        return (
          <div
            key={item.id}
            className="ds-tabs__panel"
            role="tabpanel"
            id={base + '-panel-' + item.id}
            aria-labelledby={base + '-tab-' + item.id}
            tabIndex={0}
            hidden={!isActive}
          >
            {item.content}
          </div>
        );
      })}
    </div>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { Tabs } from './Tabs';

const items = [
  { id: 'account', label: 'Account', content: 'Update your account details.' },
  { id: 'billing', label: 'Billing', content: 'Manage payment methods and invoices.' },
  { id: 'notifications', label: 'Notifications', content: 'Choose what you get notified about.' },
];

const meta = {
  title: 'Components/Tabs',
  component: Tabs,
  tags: ['autodocs'],
  args: { label: 'Settings', items },
} satisfies Meta<typeof Tabs>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
export const BillingActive: Story = { args: { defaultActiveId: 'billing' } };
`;

  const test = `${HEADER}import { afterEach, describe, expect, it } from 'vitest';
import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { expectNoAxeViolations } from '../testing/axe';
import { Tabs } from './Tabs';

afterEach(cleanup);

const items = [
  { id: 'account', label: 'Account', content: 'Account panel' },
  { id: 'billing', label: 'Billing', content: 'Billing panel' },
  { id: 'notifications', label: 'Notifications', content: 'Notifications panel' },
];

describe('Tabs accessibility', () => {
  it('has no axe violations in the default state', async () => {
    const { container } = render(<Tabs label="Settings" items={items} />);
    await expectNoAxeViolations(container);
  });

  it('moves focus and selection with ArrowRight, including wrap at the end', async () => {
    const user = userEvent.setup();
    const { container } = render(<Tabs label="Settings" items={items} />);

    await user.tab();
    expect(document.activeElement).toBe(screen.getByRole('tab', { name: 'Account' }));

    await user.keyboard('{ArrowRight}{ArrowRight}');
    const notifications = screen.getByRole('tab', { name: 'Notifications' });
    expect(document.activeElement).toBe(notifications);
    expect(notifications.getAttribute('aria-selected')).toBe('true');

    await user.keyboard('{ArrowRight}');
    const account = screen.getByRole('tab', { name: 'Account' });
    expect(document.activeElement).toBe(account);
    expect(account.getAttribute('aria-selected')).toBe('true');

    await expectNoAxeViolations(container);
  });
});
`;

  return { name: 'Tabs', component, story, test };
}

export function iconButtonTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface IconButtonProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'children'> {
  icon: React.ReactNode;
  /** Required — IconButton has no visible text, so this is its only accessible name. */
  'aria-label': string;
  variant?: 'primary' | 'secondary' | 'danger';
  size?: 'sm' | 'md' | 'lg';
}

/**
 * Icon-only button. \`aria-label\` is required at the type level so a call
 * site can't omit it; in dev mode we also catch the one thing TypeScript
 * can't — an aria-label that's present but empty or whitespace-only.
 */
export function IconButton({
  icon,
  variant = 'primary',
  size = 'md',
  type = 'button',
  disabled,
  className,
  'aria-label': ariaLabel,
  ...rest
}: IconButtonProps) {
  // globalThis-based so this shipped source doesn't require the consumer's
  // tsconfig to have @types/node just to resolve a bare \`process\` global.
  const nodeEnv = (globalThis as { process?: { env?: { NODE_ENV?: string } } }).process?.env
    ?.NODE_ENV;
  if (nodeEnv !== 'production' && ariaLabel.trim() === '') {
    console.error('IconButton: aria-label must not be empty — it is this button\\'s only accessible name.');
  }
  const classes = [
    'ds-button',
    'ds-button--icon',
    'ds-button--' + variant,
    'ds-button--' + size,
    className,
  ]
    .filter(Boolean)
    .join(' ');
  return (
    <button
      type={type}
      className={classes}
      disabled={disabled}
      aria-label={ariaLabel}
      {...rest}
    >
      <span aria-hidden="true">{icon}</span>
    </button>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { IconButton } from './IconButton';

const trashIcon = (
  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
    <path
      d="M2 4h12M6 4V2h4v2M3 4l1 10h8l1-10"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

const meta = {
  title: 'Components/IconButton',
  component: IconButton,
  tags: ['autodocs'],
  args: { icon: trashIcon, 'aria-label': 'Delete item' },
} satisfies Meta<typeof IconButton>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Primary: Story = {};
export const Secondary: Story = { args: { variant: 'secondary' } };
export const Danger: Story = { args: { variant: 'danger' } };
export const Small: Story = { args: { size: 'sm' } };
export const Large: Story = { args: { size: 'lg' } };
export const Disabled: Story = { args: { disabled: true } };
`;

  const test = axeTest(
    'IconButton',
    `  const trashIcon = (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <path
        d="M2 4h12M6 4V2h4v2M3 4l1 10h8l1-10"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );

  it('has no axe violations with a valid aria-label', async () => {
    const { container } = render(
      <main>
        <IconButton icon={trashIcon} aria-label="Delete item" />
        <IconButton icon={trashIcon} aria-label="Delete item" variant="secondary" />
        <IconButton icon={trashIcon} aria-label="Delete item" variant="danger" />
        <IconButton icon={trashIcon} aria-label="Delete item" disabled />
      </main>,
    );
    await expectNoAxeViolations(container);
  });
`,
  );

  return { name: 'IconButton', component, story, test };
}

export function allTemplates(_tokens: ResolvedTokens): ComponentFiles[] {
  return [
    buttonTemplate(),
    textFieldTemplate(),
    badgeTemplate(),
    alertTemplate(),
    checkboxTemplate(),
    switchTemplate(),
    radioGroupTemplate(),
    selectTemplate(),
    tabsTemplate(),
    iconButtonTemplate(),
  ];
}
