import type { ResolvedTokens } from '../tokens/schema.js';

export interface ComponentFiles {
  name: string;
  component: string;
  story: string;
  test: string;
}

const HEADER = '// Generated by design-system-generator — do not edit by hand.\n';

function axeTest(name: string, renderCalls: string): string {
  return `${HEADER}import { describe, it } from 'vitest';
import { render } from '@testing-library/react';
import { expectNoAxeViolations } from '../testing/axe';
import { ${name} } from './${name}';

describe('${name} accessibility', () => {
${renderCalls}
});
`;
}

export function buttonTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  /** Visual style. Every variant meets WCAG AA contrast by construction. */
  variant?: 'primary' | 'secondary' | 'danger';
  size?: 'sm' | 'md' | 'lg';
  /** Announces a busy state to assistive technology and blocks interaction. */
  loading?: boolean;
}

export function Button({
  variant = 'primary',
  size = 'md',
  loading = false,
  type = 'button',
  disabled,
  className,
  children,
  ...rest
}: ButtonProps) {
  const classes = ['ds-button', 'ds-button--' + variant, 'ds-button--' + size, className]
    .filter(Boolean)
    .join(' ');
  return (
    <button
      type={type}
      className={classes}
      disabled={disabled || loading}
      aria-busy={loading || undefined}
      {...rest}
    >
      {children}
    </button>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { Button } from './Button';

const meta = {
  title: 'Components/Button',
  component: Button,
  tags: ['autodocs'],
  args: { children: 'Save changes' },
} satisfies Meta<typeof Button>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Primary: Story = {};
export const Secondary: Story = { args: { variant: 'secondary' } };
export const Danger: Story = { args: { variant: 'danger', children: 'Delete account' } };
export const Loading: Story = { args: { loading: true, children: 'Saving…' } };
export const Small: Story = { args: { size: 'sm' } };
export const Large: Story = { args: { size: 'lg' } };
`;

  const test = axeTest(
    'Button',
    `  it('has no axe violations across variants', async () => {
    const { container } = render(
      <main>
        <Button>Primary</Button>
        <Button variant="secondary">Secondary</Button>
        <Button variant="danger">Danger</Button>
        <Button loading>Loading</Button>
        <Button disabled>Disabled</Button>
      </main>,
    );
    await expectNoAxeViolations(container);
  });
`,
  );

  return { name: 'Button', component, story, test };
}

export function textFieldTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface TextFieldProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'id' | 'aria-describedby'> {
  /** Visible label — always rendered and programmatically associated. */
  label: string;
  /** Optional helper text, linked via aria-describedby. */
  description?: string;
  /** Validation message. Sets aria-invalid and is announced politely. */
  error?: string;
}

export function TextField({ label, description, error, required, ...rest }: TextFieldProps) {
  const id = React.useId();
  const descriptionId = id + '-description';
  const errorId = id + '-error';
  const describedBy =
    [description ? descriptionId : null, error ? errorId : null].filter(Boolean).join(' ') ||
    undefined;

  return (
    <div className="ds-field">
      <label className="ds-field__label" htmlFor={id}>
        {label}
        {required ? <span aria-hidden="true"> *</span> : null}
      </label>
      {description ? (
        <p className="ds-field__description" id={descriptionId}>
          {description}
        </p>
      ) : null}
      <input
        id={id}
        className="ds-input"
        aria-describedby={describedBy}
        aria-invalid={error ? true : undefined}
        required={required}
        {...rest}
      />
      <p className="ds-field__error" id={errorId} aria-live="polite">
        {error ?? ''}
      </p>
    </div>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { TextField } from './TextField';

const meta = {
  title: 'Components/TextField',
  component: TextField,
  tags: ['autodocs'],
  args: { label: 'Email address' },
} satisfies Meta<typeof TextField>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
export const WithDescription: Story = {
  args: { description: "We'll only use this to send order updates." },
};
export const Required: Story = { args: { required: true } };
export const WithError: Story = {
  args: { error: 'Enter a valid email address.', defaultValue: 'not-an-email' },
};
`;

  const test = axeTest(
    'TextField',
    `  it('has no axe violations in default, described, and error states', async () => {
    const { container } = render(
      <main>
        <TextField label="Email address" />
        <TextField label="Password" description="Must be at least 12 characters." required />
        <TextField label="Username" error="That username is taken." defaultValue="ben" />
      </main>,
    );
    await expectNoAxeViolations(container);
  });
`,
  );

  return { name: 'TextField', component, story, test };
}

export function badgeTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  tone?: 'neutral' | 'success' | 'warning' | 'danger';
}

export function Badge({ tone = 'neutral', className, children, ...rest }: BadgeProps) {
  const classes = ['ds-badge', 'ds-badge--' + tone, className].filter(Boolean).join(' ');
  return (
    <span className={classes} {...rest}>
      {children}
    </span>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { Badge } from './Badge';

const meta = {
  title: 'Components/Badge',
  component: Badge,
  tags: ['autodocs'],
  args: { children: 'Active' },
} satisfies Meta<typeof Badge>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Neutral: Story = {};
export const Success: Story = { args: { tone: 'success', children: 'Paid' } };
export const Warning: Story = { args: { tone: 'warning', children: 'Pending' } };
export const Danger: Story = { args: { tone: 'danger', children: 'Overdue' } };
`;

  const test = axeTest(
    'Badge',
    `  it('has no axe violations across tones', async () => {
    const { container } = render(
      <main>
        <Badge>Neutral</Badge>
        <Badge tone="success">Paid</Badge>
        <Badge tone="warning">Pending</Badge>
        <Badge tone="danger">Overdue</Badge>
      </main>,
    );
    await expectNoAxeViolations(container);
  });
`,
  );

  return { name: 'Badge', component, story, test };
}

export function alertTemplate(): ComponentFiles {
  const component = `${HEADER}import * as React from 'react';
import '../styles.css';

export interface AlertProps extends React.HTMLAttributes<HTMLDivElement> {
  tone?: 'info' | 'success' | 'warning' | 'danger';
  title?: string;
}

/**
 * Danger alerts use role="alert" (assertive) because they demand attention;
 * everything else uses role="status" (polite) to avoid interrupting
 * screen-reader users mid-task.
 */
export function Alert({ tone = 'info', title, className, children, ...rest }: AlertProps) {
  const classes = ['ds-alert', 'ds-alert--' + tone, className].filter(Boolean).join(' ');
  const role = tone === 'danger' ? 'alert' : 'status';
  return (
    <div className={classes} role={role} {...rest}>
      <div>
        {title ? <p className="ds-alert__title">{title}</p> : null}
        {children}
      </div>
    </div>
  );
}
`;

  const story = `${HEADER}import type { Meta, StoryObj } from '@storybook/react';
import { Alert } from './Alert';

const meta = {
  title: 'Components/Alert',
  component: Alert,
  tags: ['autodocs'],
  args: { title: 'Heads up', children: 'Your trial ends in 3 days.' },
} satisfies Meta<typeof Alert>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Info: Story = {};
export const Success: Story = {
  args: { tone: 'success', title: 'Saved', children: 'Your changes are live.' },
};
export const Warning: Story = {
  args: { tone: 'warning', title: 'Storage almost full', children: 'You have 2% remaining.' },
};
export const Danger: Story = {
  args: { tone: 'danger', title: 'Payment failed', children: 'Update your card to continue.' },
};
`;

  const test = axeTest(
    'Alert',
    `  it('has no axe violations across tones', async () => {
    const { container } = render(
      <main>
        <Alert title="Heads up">Your trial ends in 3 days.</Alert>
        <Alert tone="success" title="Saved">Your changes are live.</Alert>
        <Alert tone="warning" title="Storage almost full">You have 2% remaining.</Alert>
        <Alert tone="danger" title="Payment failed">Update your card to continue.</Alert>
      </main>,
    );
    await expectNoAxeViolations(container);
  });
`,
  );

  return { name: 'Alert', component, story, test };
}

export function allTemplates(_tokens: ResolvedTokens): ComponentFiles[] {
  return [buttonTemplate(), textFieldTemplate(), badgeTemplate(), alertTemplate()];
}
